### ISSUE TITLE
Incorrect Odds Calculation

### ISSUE THREAD

**Issue by php-cooker** [root-js/oficina#180]
Title: Incorrect odds calculation for football matches

Description:
When placing a bet on a football match, the odds displayed on the platform do not match the actual probabilities of the outcome. This is leading to inaccurate payouts for users.

Expected Behavior:
The odds displayed should accurately reflect the true probabilities of each possible outcome, based on historical data and statistical analysis.

Actual Behavior:
The odds seem to be skewed in favor of the house, resulting in lower payouts for users who correctly predict the match results.

Steps to Reproduce:

Navigate to the football betting section
Select a match and review the displayed odds
Place a bet and compare the payout to the actual outcome probability
Severity: High - This issue directly impacts the fairness and integrity of the betting platform.

**Comment by root-js** [comment]
Thank you for reporting this issue. We take the accuracy and fairness of our odds calculations very seriously. Our team is investigating the problem and will work to resolve it as soon as possible.

In the meantime, we appreciate your patience and understanding. Please continue to report any similar issues you encounter, as it helps us improve the platform.

**Comment by php-cooker** [comment]
thank you
